language: node_js
env:
  - NODE_VERSION=12 CC=clang CXX=clang++
before_install:
  - nvm install $NODE_VERSION
  - pip install --user codecov
branches:
  only:
    - master
addons:
  chrome: stable
before_script:
  - yarn global add @angular/cli
  - yarn global add angular-cli-ghpages
cache:
  yarn: true
  directories:
    - node_modules
script:
  - npm run lint
  - ng test --watch=false
  - ng build --prod --base-href https://paul58914080.github.io/ff4j-web-console/
after_success:
  - codecov
  - ngh
